---
- name: Clone Vutoff Repository Build Docker Image and upload it to DockerHub
  hosts: localhost
  gather_facts: no

  vars:
    image_name: "ansible-img"
    image_tag: "v0.3"
    ports_map: "5000:5000"
    build_dir: "/tmp/docker_build"
    cnt_name: "devops-ansible"
    docker_repo: "psamardzhiev/docker-ansible-image"

  tasks:
    - name: Create buld directory
      file:
        path: /tmp/docker_build
        state: directory
        mode: '0777'

    - name: Clone Vutoff github repo into the Build Directory
      ansible.builtin.git:
        repo: https://github.com/vutoff/devops-programme.git
        dest: "{{ build_dir }}"
        clone: yes

    - name: build container image
      community.docker.docker_image:
        name: "{{ image_name }}:{{ image_tag }}"
        source: build
        build:
          path: "{{ build_dir }}/"
        state: present

    - name: Start the container based on that image
      community.docker.docker_container:
        name: "{{ cnt_name }}"
        image: "{{ image_name }}:{{ image_tag }}"
        state: started
        ports:
          - "{{ ports_map }}"

    - name: Tag the compiled Docker Image with v0.3 tag and Push it to DockerHub Public Repo
      community.docker.docker_image:
        name: "{{ image_name }}"
        tag: "{{ image_tag }}"
        repository: "{{ docker_repo }}"
        push: true
        source: local

    - name: Cleans up the Docker Build Temp Directory
      ansible.builtin.file:
        state: absent
        path: "{{ build_dir }}"
