---
- name: Clone PSamardzhiev repo, build and run docker container, tag and push the image to DockerHub
  hosts: localhost
  gather_facts: no

  vars:
    image_name: "ansible-img"
    image_tag: "v0.2"
    ports_map: "5000:5000"
    build_dir: "/tmp/docker_build"
    cnt_name: "devops-ansible"
    docker_repo: "psamardzhiev/docker-ansible-image"
    git_repo: "https://github.com/PSamardzhiev/devops-programme.git"

  tasks:
    - name: Create temp build directory
      file:
        path: /tmp/docker_build
        state: directory
        mode: '0777'

    - name: Clone PSamardzhiev GitHub repo to build directory
      ansible.builtin.git:
        repo: "{{ git_repo }}"
        dest: "{{ build_dir }}"
        clone: yes

    - name: Build, tag and push the image to Dockerhub
      community.docker.docker_image:
        name: "{{ image_name }}:{{ image_tag }}"
        build:
          path: "{{ build_dir }}/"
        name: "{{ image_name }}"
        tag: "{{ image_tag }}"
        repository: "{{ docker_repo }}"
        push: true
        source: build
        state: present

<<<<<<< HEAD
    - name: Starts container based on the image built from the previous task
=======
    - name: Spin-up container based on build image
>>>>>>> main
      community.docker.docker_container:
        name: "{{ cnt_name }}"
        image: "{{ image_name }}:{{ image_tag }}"
        state: started
        ports:
          - "{{ ports_map }}"

    - name: Clean up the temp build directory
      ansible.builtin.file:
        state: absent
        path: "{{ build_dir }}"
