- name: Buld, Tag and Push Docker image to Hub
  hosts: localhost
  gather_facts: no

  vars:
    image_name: "ansible-img"
    image_tag: "v0.3"
    ports_map: "5000:5000"
    build_dir: "/tmp/docker_build"
    cnt_name: "devops-ansible"
    docker_repo: "psamardzhiev/docker-ansible-image"
    git_repo: "https://github.com/PSamardzhiev/devops-programme.git"
    usr_owner: 'ps'
    group_owner: 'ps'
    mode: '0777'

  tasks:
    - name: Create temp build directory
      file:
        path: /tmp/docker_build
        state: directory
        mode: '0777'

    - name: Copy files to Build Directory
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "{{ build_dir }}/{{ item.dest }}"
        owner: "{{ usr_owner }}"
        group: "{{ group_owner }}"
        mode: "{{ mode }}"
      with_items:
        - { src: "../Dockerfile", dest: "Dockerfile" }
        - { src: "../requirements.txt", dest: "requirements.txt" }
        - { src: "../app", dest: "" }

    - name: Load DockerHub credentials from vault
      include_vars:
        file: vault.yml
        name: dockerhub_creds

    - name: Login to DockerHub using credentials from vault
      community.docker.docker_login:
        username: "{{ dockerhub_creds.dockerhub_username }}"
        password: "{{ dockerhub_creds.dockerhub_password }}"
      no_log: yes
      register: docker_login_result

    - name: Build, tag and push the image to Dockerhub
      community.docker.docker_image:
        name: "{{ image_name }}:{{ image_tag }}"
        build:
          path: "{{ build_dir }}/"
        name: "{{ image_name }}"
        tag: "{{ image_tag }}"
        repository: "{{ docker_repo }}"
        push: true
        source: build
        state: present

    - name: Log-out from Dockerhub
      community.docker.docker_login:
        state: absent

    - name: Spin-up container based on the build image
      community.docker.docker_container:
        name: "{{ cnt_name }}"
        image: "{{ image_name }}:{{ image_tag }}"
        state: started
        ports:
          - "{{ ports_map }}"

    - name: Clean up the temp build directory
      ansible.builtin.file:
        state: absent
        path: "{{ build_dir }}"
