---
- name: Authenticate with Docker Hub using Ansible Modules
  hosts: localhost
  gather_facts: false  # We don't need to gather facts for this task

  tasks:
    - name: Load Docker Hub credentials from vault
      include_vars:
        file: dockerhub_vault.yml
        name: dockerhub_creds

    - name: Log in to Docker Hub
      community.docker.docker_login:
        username: "{{ dockerhub_creds.dockerhub_username }}"
        password: "{{ dockerhub_creds.dockerhub_password }}"
      no_log: yes
      register: docker_login_result

    - name: Check Docker login status
      fail:
        msg: "Failed to log in to Docker Hub"
      when: not docker_login_result.changed

    - name: Logout from DockerHub
      docker_login:
        state: absent

