---
- name: Buld Docker Container and Push it to DockerHub
  hosts: localhost
  gather_facts: no

  vars:
    image_name: "psamardzhiev/docker-ansible-image"
    image_tag: "v0.1"
    ports_map: "5000:5000"
    build_dir: "/tmp/docker_build"
    cnt_name: "devops-ansible"


  tasks:
    - name: create build directory
      file:
        path: /tmp/docker_build
        state: directory
        owner: ps
        group: ps
        mode: '0777'
    - name: copy Dockerfile
      copy:
        src: ./Dockerfile
        dest: "{{ build_dir }}/Dockerfile"
        owner: ps
        group: ps
        mode: '0777'

    - name: copy Container Requirements
      copy:
        src: ./requirements.txt
        dest: "{{ build_dir }}/requirements.txt"
        owner: ps
        group: ps
        mode: '0777'

    - name: copy Container Requirements
      copy:
        src: ./app
        dest: "{{ build_dir }}/"
        owner: ps
        group: ps
        mode: '0777'

    - name: build container image
      community.docker.docker_image:
        name: "{{ image_name }}:{{ image_tag }}"
        source: build
        build:
          path: "{{ build_dir }}/"
        state: present

    - name: Start the container
      community.docker.docker_container:
        name: "{{ cnt_name }}"
        image: "{{ image_name }}:{{ image_tag }}"
        state: started
        ports: "{{ ports_map }}"
