---

- name: Git Checkout and build docker image
  hosts: localhost

  vars:
    docker_registry: "PSamardzhiev"
    docker_image_name: "python-app"
    docker_image_tag: "v0.1"
    git_app_dir: "gitrepo"

  tasks:
    - name: Create git repo directory
      file:
        path: "{{ ansible_env.HOME }}/{{ git_app_dir }}"
        state: directory

    - name: Print a message
      debug:
        msg: "Directory '{{ ansible_env.HOME }}/{{ git_app_dir }}' has been created."

    - name: GitHub Checkout Repo
      ansible.builtin.git:
        repo: git@github.com:PSamardzhiev/DevOps.git
        dest: "{{ ansible_env.HOME }}/{{ git_app_dir }}"
        key_file: /home/ps/.ssh/id_rsa
        accept_hostkey: yes
      environment:
        GIT_SSH_COMMAND: "ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"

    - name: Build image with arguments
      community.docker.docker_image:
        name: "{{ docker_image_name }}:{{ docker_image_tag }}"
        build:
          path: "{{ ansible_env.HOME }}/{{ git_app_dir }}/L4-Docker-pt2/app"
        source: build

    - name: 
      community.docker.docker_container:
        name: "{{ docker_image_name }}"
        image: "{{ docker_image_name }}:{{ docker_image_tag }}"
        state: started
        ports:
          - "8080:80"

